const express = require('express')
const { register, getProfile, logout,updateprofile } = require('../controller/userController')
const {get_all_location} = require('../controller/locationController')
const {create_booking,get_booking,cancel_booking} = require('../controller/bookingController')
const {login} =require('../controller/userController')
const {protect} = require('../middleware/handlerFile')
const router = express.Router()
router.post("/api/register",register)
router.post("/api/login",login)
router.get("/api/view_profile",protect,getProfile)
router.post("/api/logout",protect,logout)
// router.post("/logout",protect,logout)
router.put("/api/update_profile",protect,updateprofile)
router.get("/api/get_all_location",protect,get_all_location)
router.post("/api/create_booking",protect,create_booking)
router.get("/api/get_booking",protect,get_booking)
router.put("/api/cancel_booking",protect,cancel_booking)
// router.get("/get_all_profile",protect,getProfile)
module.exports =router